export const ADD_NEW_EPISODE_REQUEST = "ADD_NEW_EPISODE_REQUEST";
export const ADD_NEW_EPISODE_SUCCESS = "ADD_NEW_EPISODE_SUCCESS";
export const ADD_NEW_EPISODE_FAIL = "ADD_NEW_EPISODE_FAIL";
export const ADD_NEW_EPISODE_RESET = "ADD_NEW_EPISODE_RESET";

export const EDIT_EPISODE_REQUEST = "EDIT_EPISODE_REQUEST";
export const EDIT_EPISODE_SUCCESS = "EDIT_EPISODE_SUCCESS";
export const EDIT_EPISODE_FAIL = "EDIT_EPISODE_FAIL";
export const EDIT_EPISODE_RESET = "EDIT_EPISODE_RESET";

export const GET_EPISODE_REQUEST = "GET_EPISODE_REQUEST";
export const GET_EPISODE_SUCCESS = "GET_EPISODE_SUCCESS";
export const GET_EPISODE_FAIL = "GET_EPISODE_FAIL";

export const GET_EPISODES_REQUEST = "GET_EPISODES_REQUEST";
export const GET_EPISODES_SUCCESS = "GET_EPISODES_SUCCESS";
export const GET_EPISODES_FAIL = "GET_EPISODES_FAIL";

export const GET_HIGHEST_RATED_EPISODES_REQUEST =
  "GET_HIGHEST_RATED_EPISODES_REQUEST";
export const GET_HIGHEST_RATED_EPISODES_SUCCESS =
  "GET_HIGHEST_RATED_EPISODES_SUCCESS";
export const GET_HIGHEST_RATED_EPISODES_FAIL =
  "GET_HIGHEST_RATED_EPISODES_FAIL";

export const GET_EPISODES_FROM_THE_LATEST_SEASON_REQUEST =
  "GET_EPISODES_FROM_THE_LATEST_SEASON_REQUEST";
export const GET_EPISODES_FROM_THE_LATEST_SEASON_SUCCESS =
  "GET_EPISODES_FROM_THE_LATEST_SEASON_SUCCESS";
export const GET_EPISODES_FROM_THE_LATEST_SEASON_FAIL =
  "GET_EPISODES_FROM_THE_LATEST_SEASON_FAIL";

export const DELETE_EPISODE_REQUEST = "DELETE_EPISODE_REQUEST";
export const DELETE_EPISODE_SUCCESS = "DELETE_EPISODE_SUCCESS";
export const DELETE_EPISODE_FAIL = "DELETE_EPISODE_FAIL";
