export const MAKE_RATE_REQUEST = "MAKE_RATE_REQUEST";
export const MAKE_RATE_SUCCESS = "MAKE_RATE_SUCCESS";
export const MAKE_RATE_FAIL = "MAKE_RATE_FAIL";

export const GET_RATING_REQUEST = "GET_RATING_REQUEST";
export const GET_RATING_SUCCESS = "GET_RATING_SUCCESS";
export const GET_RATING_FAIL = "GET_RATING_FAIL";

export const GET_AVERAGE_RATING_REQUEST = "GET_AVERAGE_RATING_REQUEST";
export const GET_AVERAGE_RATING_SUCCESS = "GET_AVERAGE_RATING_SUCCESS";
export const GET_AVERAGE_RATING_FAIL = "GET_AVERAGE_RATING_FAIL";

export const DELETE_RATING_REQUEST = "DELETE_RATING_REQUEST";
export const DELETE_RATING_SUCCESS = "DELETE_RATING_SUCCESS";
export const DELETE_RATING_FAIL = "DELETE_RATING_FAIL";

export const GET_USER_RATING_REQUEST = "GET_USER_RATING_REQUEST";
export const GET_USER_RATING_SUCCESS = "GET_USER_RATING_SUCCESS";
export const GET_USER_RATING_FAIL = "GET_USER_RATING_FAIL";
