export const GET_SEASONS_REQUEST = "GET_SEASONS_REQUEST";
export const GET_SEASONS_SUCCESS = "GET_SEASONS_SUCCESS";
export const GET_SEASONS_FAIL = "GET_SEASONS_FAIL";

export const GET_SEASONS_BY_NUM_REQUEST = "GET_SEASONS_BY_NUM_REQUEST";
export const GET_SEASONS_BY_NUM_SUCCESS = "GET_SEASONS_BY_NUM_SUCCESS";
export const GET_SEASONS_BY_NUM_FAIL = "GET_SEASONS_BY_NUM_FAIL";

export const CREATE_SEASONS_REQUEST = "CREATE_SEASONS_REQUEST";
export const CREATE_SEASONS_SUCCESS = "CREATE_SEASONS_SUCCESS";
export const CREATE_SEASONS_FAIL = "CREATE_SEASONS_FAIL";
export const CREATE_SEASONS_RESET = "CREATE_SEASONS_RESET";

export const UPDATE_SEASONS_REQUEST = "UPDATE_SEASONS_REQUEST";
export const UPDATE_SEASONS_SUCCESS = "UPDATE_SEASONS_SUCCESS";
export const UPDATE_SEASONS_FAIL = "UPDATE_SEASONS_FAIL";
export const UPDATE_SEASONS_RESET = "UPDATE_SEASONS_RESET";
