export const ADD_NEW_VIDEO_REQUEST = "ADD_NEW_VIDEO_REQUEST";
export const ADD_NEW_VIDEO_SUCCESS = "ADD_NEW_VIDEO_SUCCESS";
export const ADD_NEW_VIDEO_FAIL = "ADD_NEW_VIDEO_FAIL";

export const GET_VIDEO_REQUEST = "GET_VIDEO_REQUEST";
export const GET_VIDEO_SUCCESS = "GET_VIDEO_SUCCESS";
export const GET_VIDEO_FAIL = "GET_VIDEO_FAIL";

export const EDIT_VIDEO_REQUEST = "EDIT_VIDEO_REQUEST";
export const EDIT_VIDEO_SUCCESS = "EDIT_VIDEO_SUCCESS";
export const EDIT_VIDEO_FAIL = "EDIT_VIDEO_FAIL";

export const DELETE_VIDEO_REQUEST = "DELETE_VIDEO_REQUEST";
export const DELETE_VIDEO_SUCCESS = "DELETE_VIDEO_SUCCESS";
export const DELETE_VIDEO_FAIL = "DELETE_VIDEO_FAIL";
